/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [idDeviceMaster]
      ,[DeviceID]
      ,[IMEINO]
      ,[SIM_NUMBER]
      ,[PlantCode]
      ,[IsActive]
      ,[IsVehAssign]
      ,[AssignVehNo]
      ,[CreatedDate]
      ,[ModifiedDate]
      ,[AssignVehDate]
      ,[NotWorkingReason]
      ,[Remarks]
      ,[IsOnTrip]
      ,[IsRepair]
      ,[ModifiedBy]
      ,[Capacity]
  FROM [GEORTD_ERSO_VTS].[dbo].[DeviceMaster] where AssignVehNo = ''